### ISSUE TITLE
Not defined..

### ISSUE THREAD

**Issue by JohnMcLear** [manuels/ep_latex#4] opened 2013-01-22 19:56 UTC
```
Couldn't find translation key pad.toolbar.latex.compile html10n.js:762
Failed to load resource: the server responded with a status of 404 (Not Found) http://10.0.0.219:9001/static/plugins/ep_latex/static/js/texlive.js/website/pdftex.js/release/pdftex-webworker.js?_=1358884503884
Failed to load resource: the server responded with a status of 404 (Not Found) http://10.0.0.219:9001/static/plugins/ep_latex/static/js/texlive.js/website/pdftex.js/release/pdftex.js?_=1358884503886
Failed to load resource: the server responded with a status of 404 (Not Found) http://10.0.0.219:9001/static/plugins/ep_latex/static/js/texlive.js/website/texlive.js?_=1358884503886
Object
 pad.js:332
Object
 pad.js:3341
Uncaught ReferenceError: PDFTeX is not defined sKFMHKUJHO:19
```

**Comment by JohnMcLear** [comment] 2013-01-22 19:57
due to https://github.com/manuels/ep_latex/issues/3

**Comment by manuels** [comment] 2013-01-22 20:14
Yes, it's not ready for the npm, yet.
However it works fine if you tell git to download all submodules.

Is it fine if we close this bug and mark it as a duplicate of #3?

**Comment by JohnMcLear** [comment] 2013-01-22 20:46
Yea prolly, btw, I tried to git clone the read only package but it's HUGE..  Is it supposed to be that big?

**Comment by manuels** [comment] 2013-01-22 20:59
Well, it includes all TeX Live files (although currently it does not support all packages).

**Closed as completed** 2013-01-23 22:55 UTC
